# Use the official Node.js image as the base image
FROM node:-alpine

# Set the working directory
WORKDIR /

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . ./

# Build the React app
RUN npm run build

# Use a lightweight server to serve the built app
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Expose the port on which the app will run
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
